services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    container_name: keycloak-dev
    command:
      - start-dev
      - --features=scripts
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_SPI_USER_STORAGE_POLL_APP_POSTGRES_V1_PROVIDER_JDBC_URL: "jdbc:postgresql://db:5432/pmp_db_local"
      KC_SPI_USER_STORAGE_POLL_APP_POSTGRES_V1_PROVIDER_DB_USERNAME: "postgres"
      KC_SPI_USER_STORAGE_POLL_APP_POSTGRES_V1_PROVIDER_DB_PASSWORD: "postgres"
      KC_LOG_LEVEL: "DEBUG,org.keycloak.provider:TRACE,org.keycloak.services:TRACE"
    volumes:
      # - ../spis/user-auth/target/user-auth-1.0-SNAPSHOT.jar:/opt/keycloak/providers/user-auth-1.0-SNAPSHOT.jar
      - ../spis/policy-provider/target/policy-provider-1.0-SNAPSHOT.jar:/opt/keycloak/providers/policy-provider-1.0-SNAPSHOT.jar

      # - ../spis/user-auth/target/libs:/opt/keycloak/providers/
    networks:
      - poll-app-network

networks:
  poll-app-network:
    external: true