services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    container_name: keycloak-dev
    command: start-dev --log-level=DEBUG
    ports:
      - "8080:8080"
      - "8787:8787" # Debug port
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_SPI_USER_STORAGE_POLL_APP_POSTGRES_V1_PROVIDER_JDBC_URL: "jdbc:postgresql://db:5432/pmp_db_local"
      KC_SPI_USER_STORAGE_POLL_APP_POSTGRES_V1_PROVIDER_DB_USERNAME: "postgres"
      KC_SPI_USER_STORAGE_POLL_APP_POSTGRES_V1_PROVIDER_DB_PASSWORD: "postgres"

      KC_LOG_LEVEL: "info,com.konrad.keycloak.storage:debug,org.keycloak.storage:debug"

    volumes:
      - ../spis/user-auth/target/user-auth-1.0-SNAPSHOT.jar:/opt/keycloak/providers/user-auth-1.0-SNAPSHOT.jar
      - ../spis/token-exchange/target/token-exchange-1.0-SNAPSHOT.jar:/opt/keycloak/providers/token-exchange-1.0-SNAPSHOT.jar
      - ../spis/protocol-mapper-claims/target/protocol-mapper-claims-1.0-SNAPSHOT.jar:/opt/keycloak/providers/protocol-mapper-claims-1.0-SNAPSHOT.jar
    networks:
      - poll-app-network

networks:
  poll-app-network:
    external: true